import Link from "next/link"

export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <header className="py-6">
          <div className="flex justify-between items-center">
            <h1 className="text-2xl font-bold text-gray-900">WarmIntro</h1>
            <Link
              href="/auth/signin"
              className="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-6 rounded-lg transition-colors"
            >
              Sign In
            </Link>
          </div>
        </header>

        {/* Hero Section */}
        <main className="py-20">
          <div className="text-center max-w-3xl mx-auto">
            <h1 className="text-5xl font-bold text-gray-900 mb-6">
              AI-Powered Warm Networking
            </h1>
            <p className="text-xl text-gray-600 mb-8">
              Connect with industry professionals through meaningful introductions.
              Find your warm contacts, generate personalized emails, and grow
              your network.
            </p>
            <div className="flex gap-4 justify-center">
              <Link
                href="/auth/signin"
                className="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-8 rounded-lg transition-colors"
              >
                Get Started
              </Link>
              <Link
                href="#features"
                className="bg-white hover:bg-gray-50 text-gray-900 font-semibold py-3 px-8 rounded-lg transition-colors border border-gray-300"
              >
                Learn More
              </Link>
            </div>
          </div>

          {/* Features Section */}
          <div id="features" className="mt-32 grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white rounded-lg shadow-lg p-6">
              <h3 className="text-xl font-semibold text-gray-900 mb-3">
                Smart Matching
              </h3>
              <p className="text-gray-600">
                Find professionals with shared connections, interests, and
                backgrounds using AI-powered matching.
              </p>
            </div>
            <div className="bg-white rounded-lg shadow-lg p-6">
              <h3 className="text-xl font-semibold text-gray-900 mb-3">
                AI Email Generation
              </h3>
              <p className="text-gray-600">
                Get personalized, warm introduction emails generated by AI based
                on your shared connections.
              </p>
            </div>
            <div className="bg-white rounded-lg shadow-lg p-6">
              <h3 className="text-xl font-semibold text-gray-900 mb-3">
                Track Your Network
              </h3>
              <p className="text-gray-600">
                Monitor your networking efforts with analytics and track your
                growing professional network.
              </p>
            </div>
          </div>
        </main>
      </div>
    </div>
  )
}
